### PR TITLE
Adds Sqooba Testimonial

### PR DESCRIPTION
**Pull request by nsanglar**
Adds Sqooba Testimonial

### CODE REVIEW

**Comment by imduffy15** [comment]
👍

**Comment by marky-mark** [comment]
Thank you :) 👍

**Comment by marky-mark** [comment]
👍

**Comment by nsanglar** [comment]
Thanks! In the near future I still have some work to push here about kerberos support, as we are working with Kerberized clusters :)

**Comment by marky-mark** [comment]
Will be happy to work with you on getting the changes you need in

**Comment by marky-mark** [comment]
@imduffy15 might be worth a oauth 2 endpoint aswell?

**Pull request merged**
