### PR TITLE
added latest tag on every build

### PR DESCRIPTION
**Pull request by marky-mark**
Issue #36

### CODE REVIEW

**Comment by marky-mark** [comment]
👍

**Comment by dr4ke616** [comment]
👍

**Comment by imduffy15** [comment]
👍

**Comment by imduffy15** [comment]
I'm unsure why @marky-mark +1 didn't work. The organisation membership is public and he has all the necessary permissions.

**Comment by marky-mark** [comment]
All i'll say is.....Yes Remora!!!

**Pull request merged**
