### PR TITLE
Allow to override root log level

### PR DESCRIPTION
**Pull request by dtrsan**
Allow to override root log level via `JAVA_OPTS`.

### CODE REVIEW

**Comment by regispl** [comment]
👍

**Comment by dtrsan** [comment]
:+1:

**Comment by brendanmaguire** [comment]
:+1:

**Comment by OneCricketeer** [comment]
Sorry, but why is this needed?

You can always just provide your own file. You don't need a variable 

` -Dlogback.configurationFile=/path/to/config.xml`

**Comment by dtrsan** [comment]
Yes, I can extend the image but this is exactly what I'm trying to avoid. It adds additional complexity to the deployment pipeline. I consider extending the image shouldn't be necessary when you just need to silence debug/info logging.

**Comment by ePaul** [comment]
:-1:

**Comment by dtrsan** [comment]
:+1:

**Comment by dtrsan** [comment]
:+1:

**Comment by regispl** [comment]
👍

**Comment by OneCricketeer** [comment]
You only responded to extending the image, which I agree adds complexity, but most companies maintain their own internal registries anyway, full of extended images that alter usernames, install certifcates, etc. 

Still, what about mounting a volume for the file? Most companies also have specific logging frameworks that need to collect different log formats (JSON logging, for example)... Why not make the format a variable as well?

**Comment by dtrsan** [comment]
> You only responded to extending the image, which I agree adds complexity, but most companies maintain their own internal registries anyway, full of extended images that alter usernames, install certifcates, etc.

I agree with all you said. It is also possible to let agents to filter out the logs or define to filter out the logs on the service side during ingestion. There are multiple approaches, each one with their own pros/cons.

> 
> Still, what about mounting a volume for the file? Most companies also have specific logging frameworks that need to collect different log formats (JSON logging, for example)... Why not make the format a variable as well?

Mounting a volume is also an option but also it comes with an extra complexity. In my case this complexity is much higher than just extending the image.

Re specific logging format, I can't find any reason why not to do it. Issue https://github.com/zalando-incubator/remora/issues/73 mentions this so maybe we should move this conversation there? Let me know what exactly do you have in mind and I'll see what I can do.

**Comment by OneCricketeer** [comment]
Well, as I commented there, and here, the file can be overwritten, at ones own discretion.

**Pull request merged**
