### PR TITLE
Fix issue reported by PR #17

### PR DESCRIPTION
**Pull request by imduffy15**
Fixing the issue reported by Hugh in PR #17.

Did some housekeeping on dependencies while looking at this, see individual commit messages for more info.

### CODE REVIEW

**Comment by dr4ke616** [comment]
👍

**Comment by imduffy15** [comment]
👍

**Comment by hughobrienjet** [comment]
Looks great, thanks. 

We're trialling some tools right now but happy to stop back if it works well for us.

**Comment by imduffy15** [comment]
Cool @hughobrienjet would love to hear how you get on with them. I've heard pretty good things about https://github.com/yahoo/kafka-manager but it only recently got 0.10.x.x support.

**Pull request merged**
