### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by marky-mark**
Updated Readme with latest tag info

### CODE REVIEW

**Comment by regispl** [comment]
👍

**Comment by regispl** [comment]
👍

**Comment by marky-mark** [comment]
👍

**Comment by imduffy15** [comment]
Hey @regispl glad to see your keeping an eye on things :).

Sadly, zappr won't detect your plus one unless your part of the Zalando group and your Zalando group membership is public. If you fill out the opensource forum you'll automatically get added to the group (think its a zlive thing, can't remember, hit-up the opensource room on hipchat)

**Comment by imduffy15** [comment]
👍

**Comment by imduffy15** [comment]
👍

**Comment by marky-mark** [comment]
👍

**Pull request merged**
