### PR TITLE
Updated kafka client version to 2.2.1

### PR DESCRIPTION
**Pull request by patelprakashp**
@cricket007 @imduffy15 - Updated Kafka client version , could you please review and merge the PR. This will help a lot as so many users getting NPE using round robin assignment strategy from Kafka consumer side. Thank in advance.

### CODE REVIEW

**Comment by patelprakashp** [comment]
@marky-mark @dehora @hjacobs @leighlondon - Can someone please review and merge the PR.

**Comment by jjst** [comment]
:+1:

**Comment by imduffy15** [comment]
👍

**Comment by imduffy15** [comment]
No Zappr rights.... @hjacobs can you help out here?

**Comment by DestyNova** [comment]
👍

**Comment by DestyNova** [comment]
👍

**Comment by irishshagua** [comment]
👍

**Comment by irishshagua** [comment]
👍

**Comment by DestyNova** [comment]
@jrake-revelant can you merge?

**Comment by cricket007** [comment]
Closes #75

**Comment by patelprakashp** [comment]
@cricket007 - do you have merge permission ?

**Comment by patelprakashp** [comment]
@hjacobs or @jrake-revelant may able to merge ? thanks guys for reviewing.

**Comment by patelprakashp** [comment]
@conorclifford - Can you please draft a new release to push into repo?

**Comment by conorclifford** [comment]
@patelprakashp sorry, its unclear to me how to release this (it seems to be undocumented, and I'm not a [maintainer](https://github.com/zalando-incubator/remora/blob/master/MAINTAINERS). If someone knows the steps, I should be able to follow them though 😄

**Comment by imduffy15** [comment]
> @patelprakashp sorry, its unclear to me how to release this (it seems to be undocumented, and I'm not a maintainer). If someone knows the steps, I should be able to follow them though 😄

Just reviewing that list I think there's only two people who still work at Zalando and have valid access.

> @conorclifford - Can you please draft a new release to push into repo?

This should have been picked up by the internal Zalando CI system and created a docker image as per the https://github.com/zalando-incubator/remora/blob/master/delivery.yaml .

However, looking at the webhook response from that system it has failed for some reason. The logs are only available to Zalando employees.

Screen Shot 2020-03-25 at 20 59 18

**Comment by conorclifford** [comment]
@imduffy15 thanks - that appeared to have failed due to no release tag. I've drafted a release and re-triggered the build, hope that works.

**Comment by patelprakashp** [comment]
@conorclifford - Thank you very much , release successful. Please close the defect #74.

**Pull request merged**
