### PR TITLE
Fixes metrics refresh bug

### LINKED ISSUE #38: Metric registry incorrectly refreshed
I realized that I introduced a bug in my latest PR, the metric registry was actually not freshed once a metric was registered...
Sorry for that, I will push a PR in the next 2 minutes

### PR DESCRIPTION
**Pull request by nsanglar**
Fixes #38

### CODE REVIEW

**Comment by marky-mark** [comment]
👍

**Comment by marky-mark** [comment]
I think if you give yourself a 👍 +1 it should work, maybe

**Comment by nsanglar** [comment]
👍

**Comment by nsanglar** [comment]
It seems that I am not from zalando group :)

**Comment by nsanglar** [comment]
Any update on the PR?

**Comment by marky-mark** [comment]
@dr4ke616 @imduffy15  can you + 1

**Comment by dr4ke616** [comment]
👍

**Comment by imduffy15** [comment]
👍

**Pull request merged**
