### PR TITLE
Use cloudwatch module from aws sdk istead of the full aws-sdk-java

### LINKED ISSUE #96: Oversized Docker image due to remora depending on complete aws-sdk-java
As evidenced by a SBOM scan using `syft`, remora bundles the full aws sdk instead of selected modules. The application uses only cloudwatch. When this optimization is added, the JARs weigh 88MB instead of 407MB.

### PR DESCRIPTION
**Pull request by bocytko**
Closes #96. This change reduces the amount of dependencies pulled in during build and packaged with the Docker image.

### CODE REVIEW

**Comment by bocytko** [comment]
Build fails with 
image

**Comment by bocytko** [comment]
@dtrsan thanks. Please ping me when this is merged, so that I can rebase my PR.

**Comment by dtrsan** [comment]
> @dtrsan thanks. Please ping me when this is merged, so that I can rebase my PR.

@bocytko I merged https://github.com/zalando-incubator/remora/pull/98

**Comment by bocytko** [comment]
👍

**Comment by dtrsan** [comment]
:+1:

**Pull request merged**
