### PR TITLE
bump aws-java-sdk-cloudwatch, add aws-java-sdk-sts

### PR DESCRIPTION
**Pull request by vlal**
* Upgrade and introduce the sts package to resolve web token permssions for eks pod permissions
* https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

### CODE REVIEW

**Comment by vlal** [comment]
@conorclifford is this okay to be merged?

**Comment by conorclifford** [comment]
I suggest you reach out to the [maintainers](https://github.com/zalando-incubator/remora/blob/master/MAINTAINERS) - I'm not one of them, sorry.

**Comment by vlal** [comment]
@brendanmaguire @marky-mark good to be merge?

**Comment by brendanmaguire** [comment]
:+1:

**Comment by vlal** [comment]
@imduffy15?

**Comment by imduffy15** [comment]
👍

**Comment by imduffy15** [comment]
Afraid this requires people from Zalando who have their zalando group membership public.... I'm no longer an employee so my 👍 is not valid.

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by brendanmaguire** [comment]
:+1:

**Pull request merged**
