### PR TITLE
Prod read readme

### PR DESCRIPTION
**Pull request by marky-mark**
Updated Readme for production ready addition

### CODE REVIEW

**Comment by imduffy15** [comment]
👍

**Comment by marky-mark** [comment]
👍

**Comment by imduffy15** [comment]
@marky-mark Your membership to the zalando org needs to be public.

**Comment by marky-mark** [comment]
how do i make public..

**Comment by imduffy15** [comment]
You can do it over here: https://github.com/orgs/zalando/people?utf8=%E2%9C%93&query=mark

**Comment by marky-mark** [comment]
👍  Thanks

**Comment by marky-mark** [comment]
PR's body failed check 'contains-issue-number'?

**Comment by imduffy15** [comment]
> PR's body failed check 'contains-issue-number'?

The PR/Commit contains no description in its body. Just click the little pencil above your first post and add some details about what the change does or just "blah blah blah"

**Comment by marky-mark** [comment]
wohhoooo thanks

**Pull request merged**
