### PR TITLE
Limit AWS SDK to only Cloudwatch

### PR DESCRIPTION
**Pull request by cricket007**
This repo doesn't need Kinesis, S3, DynamoDB, etc., etc. dependencies. 

The DropWizard metrics dependency that you're including [doesn't either](https://github.com/blacklocus/metrics-cloudwatch/blob/master/build.gradle#L67)

### CODE REVIEW

**Comment by marky-mark** [comment]
👍

**Comment by marky-mark** [comment]
Thanks again

**Comment by imduffy15** [comment]
👍

**Comment by marky-mark** [comment]
👍

**Comment by imduffy15** [comment]
👍

**Pull request merged**
